pipeline {
  agent any

  tools {
    maven 'next-gen-maven'
    dockerTool 'next-gen-docker'
  }

  environment {
    DOCKER_IMAGE = "mani12345/next-gen-accounts-kf:${BUILD_NUMBER}"
    REGISTRY_CREDENTIALS = credentials('next-gen-docker')
    GIT_REPO_NAME = "next-gen-bank-helm"
    GIT_USER_NAME = "Manikanta-12345"
    GIT_REPO_URL = "https://github.com/Manikanta-12345/next-gen-bank-helm.git"
  }

  stages {

    stage('Check Docker Version') {
      steps {
        sh 'docker --version'
      }
    }

    stage('Install Helm if Missing') {
      steps {
        sh '''
          if ! command -v helm &> /dev/null; then
            echo "Helm not found. Installing..."
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            export PATH=$PATH:/usr/local/bin
          else
            echo "Helm already installed."
            helm version
          fi
        '''
      }
    }

    stage('Checkout Source') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
          cd next-gen-accounts-kf
          rm -rf target || true
          mvn clean package -DskipTests=true
        '''
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          sh '''
            cd next-gen-accounts-kf
            docker build -t ${DOCKER_IMAGE} .
          '''
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "next-gen-docker") {
            dockerImage.push()
          }
        }
      }
    }

    stage('Update Helm Chart') {
      steps {
        withCredentials([string(credentialsId: 'next-gen-git-secret', variable: 'GITHUB_TOKEN')]) {
          sh '''
            rm -rf helm-repo
            git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git helm-repo
            cd helm-repo

            git config user.email "suryamutyala757@gmail.com"
            git config user.name "Manikanta-12345"
            cp next-gen-accounts-kf/values.yaml.template next-gen-accounts-kf/values.yaml

            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" next-gen-accounts-kf/values.yaml

            git add next-gen-accounts-kf/values.yaml
            git commit -m "Update next-gen-accounts-kf image to version ${BUILD_NUMBER}"
            git push origin master
          '''
        }
      }
    }

    stage('Build Helm Dependencies') {
      steps {
        sh '''
          cd helm-repo/environments/dev-env
          helm repo add bitnami https://charts.bitnami.com/bitnami || true
          helm dependency update
          # Git config (if not set globally)
          git config user.email "suryamutyala757@gmail.com"
          git config user.name "Manikanta-12345"

          # Add and commit updated charts directory
          git add Chart.lock charts/
          git commit -m "Update Helm dependencies"

          # Push to remote
          git push origin master || true
        '''
      }
    }
  }
}
