pipeline {
  agent {
    docker {
      image 'mani12345/maven-java17-docker-agent:v2'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  environment {
    DOCKER_IMAGE = "mani12345/next-gen-configserver:${BUILD_NUMBER}"
    REGISTRY_CREDENTIALS = credentials('next-gen-docker')
  }

  stages {
    stage('Check Docker Version') {
      steps {
        sh 'docker --version'
      }
    }

    stage('Checkout') {
      steps {
        sh 'echo passed'
      }
    }

    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        sh 'cd next-gen-configserver && mvn clean package -DskipTests=true'
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          sh 'cd next-gen-configserver && docker build -t ${DOCKER_IMAGE} .'
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "next-gen-docker") {
            dockerImage.push()
          }
        }
      }
    }
  }
}
