pipeline {
  agent any

  tools {
    maven 'next-gen-maven'
    dockerTool 'next-gen-docker'
  }

  environment {
    DOCKER_IMAGE = "mani12345/next-gen-configserver:${BUILD_NUMBER}"
    REGISTRY_CREDENTIALS = credentials('next-gen-docker')
  }

  stages {
    stage('Check Docker Version') {
      steps {
        sh 'docker --version'
      }
    }

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh 'cd next-gen-configserver && mvn clean package -DskipTests=true'
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        script {
          def dockerExe = tool 'next-gen-docker'
          sh """
            cd next-gen-configserver
            ${dockerExe}/bin/docker build -t ${DOCKER_IMAGE} .
            ${dockerExe}/bin/docker login -u ${REGISTRY_CREDENTIALS_USR} -p ${REGISTRY_CREDENTIALS_PSW}
            ${dockerExe}/bin/docker push ${DOCKER_IMAGE}
          """
        }
      }
    }
  }
}
