pipeline {
  agent any

  tools {
    maven 'next-gen-maven'
    dockerTool 'next-gen-docker'
  }

  environment {
    DOCKER_IMAGE = "mani12345/next-gen-configserver:${BUILD_NUMBER}"
    REGISTRY_CREDENTIALS = credentials('next-gen-docker')
  }

  stages {
    stage('Check Docker Version') {
      steps {
        sh 'docker --version'
      }
    }

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
          cd next-gen-configserver
          rm -rf target || true
          mvn clean package -DskipTests=true
        '''
      }
    }

    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "mani12345/next-gen-configserver:${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = credentials('next-gen-docker')
      }
      steps {
        script {
          sh '''
            cd next-gen-configserver
            docker build -t ${DOCKER_IMAGE} .
          '''
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "next-gen-docker") {
            dockerImage.push()
          }
        }
      }
    }

    stage('Update Deployment File') {
      environment {
        GIT_REPO_NAME = "next-gen-bank-helm"
        GIT_USER_NAME = "Manikanta-12345"
        GIT_REPO_URL = "https://github.com/Manikanta-12345/next-gen-bank-helm.git"
      }
      steps {
        withCredentials([string(credentialsId: 'next-gen-git-secret', variable: 'GITHUB_TOKEN')]) {
          sh '''
            # Clean up any previous clone
            rm -rf helm-repo

            # Clone the Helm repo
            git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git helm-repo

            cd helm-repo

            ls -R

            # Set Git config
            git config user.email "suryamutyala757@gmail.com"
            git config user.name "Manikanta-12345"

            # Update image tag in values.yml
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" next-gen-config-server/values.yaml

            # Commit and push the change
            git add next-gen-config-server/values.yaml
            git commit -m "Update configserver image to version ${BUILD_NUMBER}"
            git push origin master
          '''
        }
      }
    }

  }
}
